GET http://localhost:5000/capsules

###
POST http://localhost:5000/capsules
Content-Type: application/json

{
    "audio_path": "mp3",
    "audio_title": "anniversaire"
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "jean@gmail.com",
    "password": "1234"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "ok@gmail.com",
    "password": "12345"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "jean@gmail.com",
    "password": "1234"
}